name: stocky
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.12
  - pip
  - pandas
  - seaborn
  - yfinance
  - requests
  - discord
  - pip:
    - table2ascii
    - finvizfinance
